// Items, weapon skills, consumables, crafting recipes and shop prices.

const ITEMS = {
  "wooden sword": { id: "weapon", damage: 3, skills: ["twin slash", "quick jab"] },
  "rusty sword": { id: "weapon", damage: 5, skills: ["twin slash", "guard breaker"] },
  sword: { id: "weapon", damage: 6, skills: ["twin slash", "guard breaker"] },
  "iron sword": { id: "weapon", damage: 9, skills: ["twin slash", "guard breaker"] },
  "steel sword": { id: "weapon", damage: 12, skills: ["precision cut", "rending slash"] },
  "knight sword": { id: "weapon", damage: 14, crit: 4, skills: ["precision cut", "guard breaker"] },
  "ember blade": { id: "weapon", damage: 14, crit: 8, skills: ["flame slash", "inferno strike"] },
  "frost sword": { id: "weapon", damage: 15, parry: 5, skills: ["precision cut", "rending slash"] },
  "fire sword": { id: "weapon", damage: 16, crit: 5, skills: ["flame slash", "inferno strike"] },
  "soul scythe": {
    id: "weapon",
    damage: 18,
    crit: 12,
    max_hp: -10,
    skills: ["soul reap", "grim embrace"],
  },
  greatsword: { id: "weapon", damage: 20, max_hp: -5, skills: ["executioner swing", "whirlwind"] },
  "demon sword": { id: "weapon", damage: 20, crit: 8, skills: ["rending slash", "soul reap"] },
  "dragon slayer": {
    id: "weapon",
    damage: 24,
    crit: 7,
    skills: ["precision cut", "executioner swing"],
  },
  "ancient blade": { id: "weapon", damage: 27, crit: 12, skills: ["precision cut", "arcane bolt"] },
  "void weapon": {
    id: "weapon",
    damage: 30,
    crit: 15,
    dodge: 5,
    skills: ["arcane bolt", "mana siphon"],
  },
  "stone axe": { id: "weapon", damage: 7, skills: ["cleave", "reckless chop"] },
  axe: { id: "weapon", damage: 10, skills: ["cleave", "reckless chop"] },
  "iron axe": { id: "weapon", damage: 11, skills: ["cleave", "reckless chop"] },
  "battle axe": { id: "weapon", damage: 15, skills: ["cleave", "guard breaker"] },
  "heavy axe": { id: "weapon", damage: 19, max_hp: 5, skills: ["cleave", "shatter"] },
  "berserker axe": {
    id: "weapon",
    damage: 22,
    max_hp: -5,
    crit: 8,
    skills: ["cleave", "reckless chop"],
  },
  "blood axe": { id: "weapon", damage: 25, crit: 10, skills: ["cleave", "soul reap"] },
  "infernal axe": { id: "weapon", damage: 26, crit: 10, skills: ["flame slash", "reckless chop"] },
  warhammer: { id: "weapon", damage: 15, max_hp: 10, skills: ["skull crusher", "shatter"] },
  "thunder hammer": {
    id: "weapon",
    damage: 24,
    max_hp: 10,
    max_energy: 1,
    skills: ["skull crusher", "arcane bolt"],
  },
  spear: { id: "weapon", damage: 8, parry: 5, skills: ["piercing thrust", "quick jab"] },
  "iron spear": { id: "weapon", damage: 10, parry: 3, skills: ["piercing thrust", "quick jab"] },
  "steel spear": { id: "weapon", damage: 14, parry: 5, skills: ["piercing thrust", "quick jab"] },
  "war spear": { id: "weapon", damage: 17, parry: 7, skills: ["piercing thrust", "whirlwind"] },
  "dragon spear": {
    id: "weapon",
    damage: 23,
    parry: 8,
    skills: ["piercing thrust", "inferno strike"],
  },
  longbow: { id: "weapon", damage: 7, dodge: 5, crit: 8, skills: ["aimed shot", "volley"] },
  "hunter bow": { id: "weapon", damage: 8, crit: 5, dodge: 3, skills: ["aimed shot", "volley"] },
  "composite bow": {
    id: "weapon",
    damage: 12,
    crit: 7,
    dodge: 5,
    skills: ["aimed shot", "volley"],
  },
  "war bow": { id: "weapon", damage: 17, crit: 9, dodge: 5, skills: ["aimed shot", "volley"] },
  "dragon bow": { id: "weapon", damage: 23, crit: 12, dodge: 7, skills: ["aimed shot", "volley"] },
  dagger: { id: "weapon", damage: 3, crit: 10, dodge: 3, skills: ["backstab", "poison cut"] },
  "poison dagger": {
    id: "weapon",
    damage: 8,
    crit: 12,
    dodge: 5,
    skills: ["backstab", "poison cut"],
  },
  frostfang: { id: "weapon", damage: 18, parry: 6, skills: ["backstab", "rending slash"] },
  flameblade: { id: "weapon", damage: 19, crit: 8, skills: ["flame slash", "inferno strike"] },
  "shadow blade": {
    id: "weapon",
    damage: 21,
    crit: 14,
    dodge: 8,
    skills: ["backstab", "mana siphon"],
  },
  "mage staff": {
    id: "weapon",
    damage: 9,
    max_hp: 10,
    max_energy: 1,
    crit: 5,
    skills: ["arcane bolt", "mana siphon"],
  },
  "cloth armor": { id: "armor", max_hp: 10, defense: 1 },
  "leather armor": { id: "armor", max_hp: 25, defense: 2 },
  armor: { id: "armor", max_hp: 40, defense: 3 },
  "hardened leather armor": { id: "armor", max_hp: 40, defense: 3 },
  chainmail: { id: "armor", max_hp: 50, defense: 4 },
  "steel armor": { id: "armor", max_hp: 60, guard: 0.05, defense: 4 },
  "iron armor": { id: "armor", max_hp: 65, defense: 5 },
  "knight armor": { id: "armor", max_hp: 80, defense: 6, guard: 0.05 },
  "orc armor": { id: "armor", max_hp: 70, defense: 6, guard: 0.05 },
  "flame armor": { id: "armor", max_hp: 70, defense: 5, guard: 0.08 },
  "frost armor": { id: "armor", max_hp: 75, defense: 6, guard: 0.08 },
  "dragon armor": { id: "armor", max_hp: 75, guard: 0.1, defense: 6 },
  "dragonscale armor": { id: "armor", max_hp: 120, defense: 9, guard: 0.15 },
  "shadow armor": { id: "armor", max_hp: 55, defense: 3, dodge: 10 },
  "shadow cloak": { id: "armor", max_hp: 20, dodge: 15, crit: 5, defense: 1, skills: ["backstab"] },
  "mystic robe": { id: "armor", max_hp: 30, max_energy: 1, dodge: 10, crit: 8, defense: 2, skills: ["arcane bolt"] },
  "berserker armor": { id: "armor", max_hp: 60, defense: 4, crit: 8 },
  "guardian armor": { id: "armor", max_hp: 100, defense: 8, guard: 0.12 },
  "demon armor": { id: "armor", max_hp: 90, defense: 7, crit: 4 },
  shield: { id: "offhand", max_hp: 25, guard: 0.2, parry: 10, defense: 2 },
  "shell shield": { id: "offhand", max_hp: 30, guard: 0.25, parry: 5, defense: 3 },
  "dragon shield": { id: "offhand", max_hp: 45, guard: 0.3, parry: 15, defense: 4 },
  helmet: { id: "head", max_hp: 15, defense: 1 },
  "feather cap": { id: "head", max_hp: 10, dodge: 10, defense: 1 },
  crown: { id: "head", max_hp: 20, crit: 10, parry: 5, defense: 1 },
  boots: { id: "feet", max_hp: 5, dodge: 8, defense: 1 },
  "wind boots": { id: "feet", max_hp: 8, dodge: 12, defense: 1 },
  "dragon boots": { id: "feet", max_hp: 15, dodge: 15, defense: 2 },
  charm: { id: "trinket", max_hp: 10, crit: 8, skills: ["quick jab"] },
  "first shard": {
    id: "trinket",
    max_hp: 25,
    max_energy: 1,
    crit: 5,
    skills: ["mana siphon"],
    description: "A fragment of the original world.",
  },
  "godslayer relic": {
    id: "trinket",
    damage: 8,
    max_hp: 50,
    max_energy: 1,
    crit: 8,
    description: "It grows stronger whenever a god stops being a god.",
  },
  "glass edge": {
    id: "trinket", damage_mult: 0.25, max_hp: -25, no_guard: 1,
    description: "+25% damage, but removes the ability to guard.",
  },
  "stormglass charm": {
    id: "trinket", dodge: 18, max_hp: -20, max_energy: -1,
    description: "+18% dodge, but -20 max HP and -1 max energy.",
  },
  "fractured crown": {
    id: "head",
    max_hp: 80,
    defense: 5,
    dodge: 8,
    description: "A crown worn by something that has forgotten its kingdom.",
  },
  edgewalker: {
    id: "weapon",
    damage: 38,
    crit: 20,
    dodge: 10,
    description: "Forged from the boundary between two states of the game.",
    skills: ["precision cut", "arcane bolt"],
  },
  "last light": {
    id: "weapon",
    damage: 45,
    crit: 25,
    max_hp: 40,
    description: "It does not glow. Everything around it simply becomes darker.",
    skills: ["soul reap", "grim embrace"],
  },
};

// Stun skills: `stagger` is the % chance to stun on a landed hit, `stun_turns` is how many
// enemy turns are lost (see the STUN balance table in combat.js for caps and immunity).
const SKILLS = {
  "twin slash": {
    desc: "Two quick slashes.",
    cost: 2,
    type: "fast",
    hits: 2,
    damage_mult: 0.7,
    name: "twin slash",
  },
  "guard breaker": {
    desc: "A crushing strike that cracks through guards. May stun for 1 turn.",
    cost: 3,
    damage_mult: 1.2,
    ignore_guard: true,
    stagger: 35,
    stun_turns: 1,
    name: "guard breaker",
  },
  cleave: {
    desc: "A heavy chop that opens a bleeding wound.",
    cost: 3,
    type: "heavy",
    damage_mult: 1.6,
    effect: { type: "bleed", chance: 70, damage: 3, turns: 3 },
    name: "cleave",
  },
  "reckless chop": {
    desc: "An all-out swing. Hits hard, but you take recoil.",
    cost: 2,
    damage_mult: 2.0,
    hit_bonus: -20,
    recoil: 6,
    name: "reckless chop",
  },
  backstab: {
    desc: "A precise strike at a weak spot. Hard to dodge.",
    cost: 2,
    type: "fast",
    damage_mult: 1.4,
    crit_bonus: 40,
    ignore_dodge: true,
    name: "backstab",
  },
  "poison cut": {
    desc: "A shallow cut with a poisoned edge.",
    cost: 2,
    type: "fast",
    damage_mult: 0.6,
    effect: { type: "poison", chance: 100, damage: 3, turns: 4 },
    name: "poison cut",
  },
  "skull crusher": {
    desc: "A bone-rattling blow that can knock the enemy senseless for 2 turns.",
    cost: 4,
    type: "heavy",
    damage_mult: 2.0,
    stagger: 45,
    stun_turns: 2,
    cooldown: 3,
    name: "skull crusher",
  },
  shatter: {
    desc: "Slam the ground to break guards. Can't be dodged. May stun for 1 turn.",
    cost: 3,
    type: "heavy",
    damage_mult: 1.3,
    ignore_guard: true,
    ignore_dodge: true,
    stagger: 25,
    stun_turns: 1,
    name: "shatter",
  },
  "piercing thrust": {
    desc: "A long thrust that slips past guards and parries.",
    cost: 2,
    damage_mult: 1.3,
    ignore_guard: true,
    ignore_parry: true,
    name: "piercing thrust",
  },
  "quick jab": {
    desc: "A cheap, accurate poke.",
    cost: 1,
    type: "fast",
    damage_mult: 0.8,
    hit_bonus: 20,
    name: "quick jab",
  },
  "aimed shot": {
    desc: "A carefully aimed arrow. Can't be parried.",
    cost: 2,
    damage_mult: 1.6,
    hit_bonus: 25,
    crit_bonus: 15,
    ignore_parry: true,
    name: "aimed shot",
  },
  volley: {
    desc: "Loose three arrows in a row. Can't be parried.",
    cost: 3,
    hits: 3,
    damage_mult: 0.6,
    ignore_parry: true,
    name: "volley",
  },
  "executioner swing": {
    desc: "A huge, slow overhead chop. A direct hit can stun for 2 turns.",
    cost: 4,
    type: "slow",
    damage_mult: 2.4,
    hit_bonus: -10,
    stagger: 25,
    stun_turns: 2,
    cooldown: 3,
    name: "executioner swing",
  },
  whirlwind: {
    desc: "Spin twice, striking all around. Can't be dodged.",
    cost: 3,
    type: "heavy",
    hits: 2,
    damage_mult: 1.0,
    ignore_dodge: true,
    name: "whirlwind",
  },
  "arcane bolt": {
    desc: "A bolt of pure magic. Nothing stops it.",
    cost: 2,
    damage_mult: 1.4,
    cooldown: 1,
    ignore_guard: true,
    ignore_parry: true,
    ignore_dodge: true,
    name: "arcane bolt",
  },
  "mana siphon": {
    desc: "Drain life from the enemy. Can't be parried.",
    cost: 3,
    damage_mult: 1.0,
    ignore_parry: true,
    lifesteal: 0.5,
    name: "mana siphon",
  },
  "precision cut": {
    desc: "A clean, accurate cut that finds weak points.",
    cost: 2,
    damage_mult: 1.5,
    hit_bonus: 15,
    crit_bonus: 30,
    name: "precision cut",
  },
  "rending slash": {
    desc: "A deep slash that leaves a bleeding wound.",
    cost: 3,
    damage_mult: 1.3,
    effect: { type: "bleed", chance: 100, damage: 4, turns: 3 },
    name: "rending slash",
  },
  "flame slash": {
    desc: "A blazing slash that may set the enemy alight.",
    cost: 3,
    damage_mult: 1.4,
    effect: { type: "burn", chance: 80, damage: 4, turns: 3 },
    name: "flame slash",
  },
  "inferno strike": {
    desc: "Unleash the blade's fire in one huge strike.",
    cost: 4,
    type: "heavy",
    damage_mult: 2.0,
    cooldown: 2,
    effect: { type: "burn", chance: 100, damage: 5, turns: 3 },
    name: "inferno strike",
  },
  "soul reap": {
    desc: "Reap the enemy's life force to heal yourself.",
    cost: 3,
    damage_mult: 1.5,
    lifesteal: 0.5,
    name: "soul reap",
  },
  "grim embrace": {
    desc: "A slow, merciless strike that ignores guards.",
    cost: 4,
    type: "slow",
    damage_mult: 2.2,
    hit_bonus: -10,
    ignore_guard: true,
    lifesteal: 0.3,
    cooldown: 2,
    name: "grim embrace",
  },
};

const USABLE_ITEMS = {
  potion: { heal: 40 },
  "greater potion": { heal: 80 },
  "small health potion": { heal: 25 },
  "health potion": { heal: 50 },
  "large health potion": { heal: 90 },
  "roast meat": { heal: 35 },
  elixir: { heal: 120, energy: 2 },
  "full heal potion": { heal: 999 },
  "phoenix potion": { heal: 999, revive: true },
  antidote: { cure: true },
  "energy tonic": { energy: 3 },
  "energy potion": { energy: 6 },
  "battle tonic": { energy: 6, buff_damage: 5 },
  "strength potion": { buff_damage: 6 },
  "defense potion": { buff_defense: 4 },
  "speed potion": { buff_dodge: 10 },
  "critical potion": { buff_crit: 10 },
  "fire resistance potion": { buff_fire_resistance: 50 },
  "frost resistance potion": { buff_frost_resistance: 50 },
  bomb: { damage: 30 },
  "smoke flask": { stun: true, stun_turns: 2 },
  "fire bomb": { damage: 24, element: "fire", effect: { type: "burn", chance: 70, damage: 4, turns: 3 } },
  "frost bomb": { damage: 18, element: "frost", effect: { type: "slow", chance: 75, damage: 0, turns: 2 } },
  "venom vial": { damage: 8, effect: { type: "poison", chance: 90, damage: 5, turns: 3 } },
  "flash powder": { stun: true, stun_turns: 1, effect: { type: "weakened", chance: 100, damage: 0, turns: 2 } },
  "ward scroll": { self: { type: "warded", turns: 3 } },
  "battle focus scroll": { self: { type: "empowered", turns: 3 } },
  "stone skin scroll": { self: { type: "fortified", turns: 3 } },
  "barrier charm": { self: { type: "shield", absorb: 28, turns: 3 } },
  "wyrmfire bomb": { damage: 32, element: "fire", effect: { type: "burn", chance: 75, damage: 5, turns: 3 } },
  "glacier flask": { damage: 27, element: "frost", effect: { type: "slow", chance: 80, damage: 0, turns: 2 } },
  "wraith ward scroll": { self: { type: "warded", turns: 4 } },
  "archivist seal": { self: { type: "shield", absorb: 42, turns: 3 } },
  "hero's gambit tonic": { buff_damage: 8, buff_crit: 8 },
};

const recipes = {
  steel: { iron: 3, coal: 1 },
  "enchanted silk": { silk: 3, crystal: 1 },
  "hardened leather": { leather: 3, coal: 1 },
  silver: { "silver ore": 3, coal: 1 },
  gold: { "gold ore": 3, coal: 1 },
  sword: { iron: 5, wood: 5 },
  "wooden sword": { wood: 5, fiber: 2 },
  "rusty sword": { iron: 4, wood: 2 },
  "iron sword": { iron: 8, wood: 3 },
  "steel sword": { steel: 6, wood: 4 },
  "knight sword": { steel: 8, wood: 3, leather: 1 },
  greatsword: { iron: 18, wood: 8, scale: 1 },
  "fire sword": { steel: 6, "ember core": 2, crystal: 1 },
  "ember blade": { steel: 4, "ember core": 2, crystal: 1 },
  "frost sword": { steel: 6, "frost crystal": 2 },
  "demon sword": { obsidian: 5, "demon horn": 2, "demon core": 1 },
  "dragon slayer": { steel: 8, "dragon scale": 3, "dragon bone": 2 },
  "ancient blade": { obsidian: 4, "ancient crystal": 3, "ancient heart": 1 },
  "void weapon": { obsidian: 5, "void crystal": 2, "demon core": 1 },
  "soul scythe": { steel: 6, "soul shard": 3, crystal: 2 },
  axe: { iron: 10, wood: 6 },
  "stone axe": { stone: 6, wood: 4 },
  "iron axe": { iron: 8, wood: 4 },
  "battle axe": { steel: 7, wood: 4 },
  "heavy axe": { steel: 10, wood: 5, stone: 3 },
  "berserker axe": { steel: 8, "demon horn": 1, "dragon bone": 1 },
  "infernal axe": { obsidian: 6, "demon horn": 3, "demon core": 1 },
  "blood axe": { steel: 8, "dragon bone": 2, "demon core": 1 },
  warhammer: { iron: 14, wood: 5, scale: 1 },
  "thunder hammer": { steel: 10, crystal: 3, gold: 1 },
  spear: { iron: 7, wood: 8, fang: 1 },
  "iron spear": { iron: 7, wood: 5 },
  "steel spear": { steel: 7, wood: 5 },
  "war spear": { steel: 10, wood: 5, fang: 2 },
  "dragon spear": { steel: 8, "dragon scale": 3, "dragon bone": 2 },
  longbow: { wood: 12, silk: 4, leather: 2 },
  "hunter bow": { wood: 7, leather: 2, fiber: 2 },
  "composite bow": { wood: 8, "hardened leather": 3, silk: 2 },
  "war bow": { steel: 4, wood: 8, silk: 3 },
  "dragon bow": { "dragon bone": 2, "dragon scale": 3, silk: 4 },
  dagger: { iron: 3, bone: 2 },
  "poison dagger": { iron: 4, silk: 2, "demon horn": 1 },
  flameblade: { steel: 6, "ember core": 3, crystal: 1 },
  frostfang: { steel: 6, "frost crystal": 2, fang: 2 },
  "shadow blade": { obsidian: 5, silk: 3, "void crystal": 1 },
  "mage staff": { wood: 10, silk: 6, crystal: 2 },
  "cloth armor": { fiber: 6 },
  "leather armor": { leather: 8, fiber: 2 },
  "hardened leather armor": { "hardened leather": 8, fiber: 2 },
  chainmail: { iron: 12, leather: 2 },
  armor: { iron: 10, wood: 3 },
  "iron armor": { iron: 16, leather: 4 },
  "steel armor": { steel: 10, leather: 4 },
  "knight armor": { steel: 16, "hardened leather": 4, silver: 1 },
  "orc armor": { steel: 12, "hardened leather": 6, "orc tusk": 1 },
  "flame armor": { steel: 10, "ember core": 3, crystal: 2 },
  "frost armor": { steel: 10, "frost crystal": 3, "hardened leather": 3 },
  "shadow armor": { obsidian: 6, silk: 5, "void crystal": 1 },
  "berserker armor": { steel: 12, "dragon bone": 2, "demon horn": 2 },
  "guardian armor": { steel: 14, "ancient crystal": 2, "ancient heart": 1 },
  "demon armor": { obsidian: 8, "demon horn": 4, "demon core": 1 },
  "dragon armor": { iron: 20, leather: 5, scale: 2 },
  "dragonscale armor": { "dragon scale": 6, "dragon bone": 3, "dragon heart": 1 },
  "mystic robe": { "enchanted silk": 4, leather: 2 },
  "shadow cloak": { silk: 8, leather: 4, fang: 2 },
  shield: { iron: 8, wood: 2 },
  "shell shield": { shell: 6, iron: 4 },
  "dragon shield": { iron: 15, scale: 2, leather: 2 },
  helmet: { iron: 6, leather: 2 },
  "feather cap": { feather: 5, silk: 2 },
  crown: { iron: 8, crystal: 3, silk: 3 },
  boots: { leather: 4, wood: 1 },
  "wind boots": { feather: 6, leather: 4 },
  "dragon boots": { leather: 6, scale: 1, silk: 2 },
  charm: { fang: 3, silk: 2 },
  "godslayer relic": { "ancient heart": 2, "ancient crystal": 8, "void crystal": 4 },
  "fractured crown": { "ancient crystal": 6, "frost crystal": 4, "void crystal": 2 },
  edgewalker: { "void crystal": 8, "demon core": 2, "ancient heart": 1 },
  "last light": { "void crystal": 15, "ancient heart": 3, "ancient crystal": 10 },
  potion: { wood: 3, coin: 10 },
  "greater potion": { wood: 5, bone: 2, coin: 25 },
  elixir: { wood: 8, crystal: 1, coin: 40 },
  "phoenix potion": { scale: 1, crystal: 2, coin: 75 },
  antidote: { wood: 2, fang: 1 },
  "energy tonic": { silk: 2, coin: 15 },
  "battle tonic": { fang: 2, crystal: 1, coin: 30 },
  "small health potion": { wood: 2, fiber: 1 },
  "health potion": { wood: 4, fiber: 2 },
  "large health potion": { wood: 7, fiber: 3, crystal: 1 },
  "full heal potion": { wood: 10, fiber: 4, "ancient crystal": 1 },
  "strength potion": { fang: 2, crystal: 1 },
  "defense potion": { iron: 2, "hardened leather": 1, crystal: 1 },
  "speed potion": { feather: 2, silk: 1, crystal: 1 },
  "critical potion": { fang: 2, crystal: 2 },
  "fire resistance potion": { "ember core": 2, crystal: 1 },
  "frost resistance potion": { "frost crystal": 2, crystal: 1 },
  "energy potion": { silk: 2, crystal: 1 },
  "roast meat": { meat: 2, wood: 1 },
  bomb: { coal: 2, iron: 1, coin: 10 },
  "smoke flask": { silk: 1, coal: 1, coin: 15 },
  "fire bomb": { coal: 2, "ember core": 1, iron: 1, coin: 18 },
  "frost bomb": { coal: 2, "frost crystal": 1, iron: 1, coin: 18 },
  "venom vial": { fang: 2, wood: 1, coin: 12 },
  "flash powder": { coal: 2, feather: 1, coin: 14 },
  "ward scroll": { silk: 2, crystal: 1, coin: 25 },
  "battle focus scroll": { silk: 2, fang: 1, coin: 22 },
  "stone skin scroll": { leather: 2, stone: 2, coin: 20 },
  "barrier charm": { crystal: 1, iron: 2, coin: 30 },
  "wyrmfire bomb": { "ember core": 1, "dragon scale": 1, coal: 2 },
  "glacier flask": { "frost crystal": 1, scale: 1, crystal: 1 },
  "wraith ward scroll": { "soul shard": 1, silk: 2, crystal: 1 },
  "archivist seal": { "ancient crystal": 2, "soul shard": 2 },
  "hero's gambit tonic": { "demon horn": 1, "ancient heart": 1, fang: 2 },
};

// Regular foes have a modest chance to teach rare formulas; linked bosses guarantee them.
const RECIPE_DISCOVERY = {
  "wyrmfire bomb": { wyvern: 18, dragon: 25, "ancient dragon": 35, "the unnamed king": 100 },
  "glacier flask": { "frost giant": 20, "the leftover": 100 },
  "wraith ward scroll": { wraith: 18, lich: 10, "the watcher": 100 },
  "archivist seal": { "archive stalker": 20, "the archivist": 100 },
  "indexer's lens": { "index hound": 100 },
  "starfall aegis": { "glasswing moth": 100 },
  ashglass: { "ashbound sentinel": 100 },
  "oathkeeper mail": { "hollow sentinel": 100 },
  "outrider's bow": { "frontier outrider": 100 },
  "choir veil": { "bellbound cantor": 100 },
  "reliquary guard": { "the bell without a tongue": 100 },
  "mosswrap boots": { mossling: 100 },
  "lantern charm": { "lantern thief": 100 },
  "mossback buckler": { "mossback guardian": 100 },
  "hero's gambit tonic": { berserker: 12, "the first hero": 100 },
  "margin seal": { "margin warden": 20, "the editor": 100 },
  "last line tonic": { "the author": 100, "the last save": 100 },
};

const SHOP_BUY = {
  wood: 8,
  iron: 15,
  leather: 12,
  bone: 10,
  fang: 18,
  silk: 15,
  coal: 20,
  crystal: 50,
  fiber: 6,
  stone: 10,
  "silver ore": 45,
  "gold ore": 70,
  potion: 25,
  antidote: 20,
  "energy tonic": 35,
  "greater potion": 60,
  elixir: 100,
  "battle tonic": 80,
  "phoenix potion": 180,
  bomb: 40,
  "smoke flask": 35,
  "fire bomb": 55, "frost bomb": 55, "venom vial": 35, "flash powder": 40,
  "ward scroll": 65, "battle focus scroll": 55, "stone skin scroll": 50, "barrier charm": 80,
  "wyrmfire bomb": 80, "glacier flask": 85, "wraith ward scroll": 100, "archivist seal": 150, "hero's gambit tonic": 120,
};

const SHOP_SELL = {
  wood: 3,
  iron: 6,
  leather: 5,
  bone: 4,
  fang: 8,
  silk: 6,
  coal: 10,
  crystal: 25,
  scale: 40,
  steel: 20,
  "enchanted silk": 20,
  shell: 12,
  feather: 10,
  "ember core": 35,
  "soul shard": 45,
  potion: 10,
  "greater potion": 25,
  antidote: 8,
  "energy tonic": 14,
  elixir: 40,
  "battle tonic": 30,
  "phoenix potion": 90,
  bomb: 18,
  "smoke flask": 15,
  "fire bomb": 25, "frost bomb": 25, "venom vial": 16, "flash powder": 18,
  "ward scroll": 30, "battle focus scroll": 25, "stone skin scroll": 22, "barrier charm": 38,
  "wyrmfire bomb": 38, "glacier flask": 40, "wraith ward scroll": 48, "archivist seal": 70, "hero's gambit tonic": 55,
  fiber: 2,
  stone: 3,
  "silver ore": 14,
  "gold ore": 22,
  silver: 40,
  gold: 60,
  "hardened leather": 15,
  obsidian: 45,
  "dragon scale": 60,
  "dragon bone": 50,
  "demon horn": 60,
  "ancient crystal": 90,
  "frost crystal": 40,
  "dragon heart": 150,
  "demon core": 140,
  "ancient heart": 250,
  "void crystal": 120,
  "orc tusk": 20,
  meat: 4,
  fur: 5,
  "rat fang": 6,
  "dire fang": 14,
  "goblin blade": 25,
  "ogre hide": 25,
  "berserker hide": 30,
  "giant hide": 35,
  "frost king core": 120,
  "roast meat": 12,
  "small health potion": 8,
  "health potion": 15,
  "large health potion": 30,
  "full heal potion": 80,
};

// ---------- Chapter 6-10 gear ----------
Object.assign(ITEMS, {
  "archive blade": {
    id: "weapon",
    damage: 52,
    crit: 26,
    max_hp: 30,
    description: "Every strike is already written down somewhere.",
    skills: ["precision cut", "soul reap"],
  },
  "hollow plate": {
    id: "armor",
    max_hp: 160,
    defense: 11,
    guard: 0.18,
    description: "Armor that held a hero up until the hero stopped.",
  },
  redline: {
    id: "weapon",
    damage: 60,
    crit: 28,
    dodge: 8,
    description: "A blade drawn as a single strikethrough.",
    skills: ["precision cut", "executioner swing"],
  },
  "inkbound seal": {
    id: "trinket",
    damage: 12,
    max_hp: 70,
    crit: 10,
    description: "A mark that only exists because someone chose to write it.",
  },
  finalis: {
    id: "weapon",
    damage: 70,
    crit: 30,
    max_hp: 60,
    description: "The last thing in the file. It cuts like a full stop.",
    skills: ["soul reap", "arcane bolt"],
  },
});
Object.assign(recipes, {
  "archive blade": { "void crystal": 20, "ancient heart": 4, "soul shard": 6 },
  "hollow plate": { "void crystal": 18, "ancient heart": 4, "ancient crystal": 12 },
  redline: { "void crystal": 25, "ancient heart": 5, "demon core": 3 },
  "inkbound seal": { "void crystal": 22, "ancient heart": 5, "ancient crystal": 14 },
  finalis: { "void crystal": 35, "ancient heart": 8, "ancient crystal": 20 },
});

Object.assign(USABLE_ITEMS, {
  "moonlit poultice": { heal: 48, cure: true },
  "salt ward": { self: { type: "warded", turns: 4 } },
  "clockwork charge": { energy: 4, buff_damage: 4 },
  "sunfire bomb": { damage: 30, element: "fire", effect: { type: "burn", chance: 85, damage: 5, turns: 3 } },
  "margin seal": { self: { type: "shield", absorb: 50, turns: 3 } },
  "last line tonic": { heal: 65, energy: 3, buff_damage: 8 },
  "field stew": { heal: 48 },
});
Object.assign(ITEMS, {
  "trailbreaker bow": { id: "weapon", damage: 15, crit: 8, dodge: 5, skills: ["aimed shot", "volley"], description: "A frontier scout's bow rebuilt around a spring-steel limb." },
  bellguard: { id: "offhand", defense: 5, guard: 0.08, max_hp: 28, description: "A small shield that hums when danger is close." },
  "nullweave coat": { id: "armor", max_hp: 82, defense: 7, dodge: 4, parry: 3, description: "Cloth woven from a place the world tried to forget." },
  "archivist's ring": { id: "trinket", max_hp: 42, crit: 6, damage: 5, description: "A catalog mark that helps its wearer find the opening." },
  "indexer's lens": { id: "trinket", max_hp: 28, crit: 9, damage: 7, description: "A brass lens that brings the weak points in a story into focus." },
  "starfall aegis": { id: "offhand", max_hp: 38, defense: 6, guard: 0.08, description: "A shield cut from the glass shell of a fallen star." },
  ashglass: { id: "weapon", damage: 21, crit: 10, skills: ["precision cut", "rending slash"], description: "A dark blade with a bright ember caught inside." },
  "oathkeeper mail": { id: "armor", max_hp: 115, defense: 9, parry: 3, description: "The last guard's oath, hammered into a coat of black iron." },
  "cartographer's compass": { id: "trinket", max_hp: 58, damage: 10, crit: 8, dodge: 5, description: "It points toward the next choice, never the easiest one." },
  "outrider's bow": { id: "weapon", damage: 12, crit: 7, dodge: 3, skills: ["aimed shot", "volley"], description: "A compact bow built for a long patrol and a quick retreat." },
  "choir veil": { id: "head", max_hp: 36, max_energy: 1, defense: 3, parry: 3, description: "A strip of ash-silk that dulls the Cathedral's dissonant chorus." },
  "reliquary guard": { id: "offhand", max_hp: 48, defense: 7, guard: 0.1, description: "A shield forged from the tongue-less bell's fractured rim." },
  "bellshard maul": { id: "weapon", damage: 24, crit: 5, skills: ["executioner swing", "shatter"], description: "A two-handed weight of resonant metal. Each swing remembers the bell that made it." },
  "mosswrap boots": { id: "boots", max_hp: 12, dodge: 4, description: "Soft boots braided from tough roadside moss. They grip loose stone without slowing you down." },
  "roadward charm": { id: "trinket", max_hp: 10, dodge: 2, description: "A brass pin recovered from an old waystone. It points toward the road home." },
  "lantern charm": { id: "trinket", max_hp: 14, crit: 3, description: "A shard of lantern glass that catches a glint just before danger moves." },
  "mossback buckler": { id: "offhand", max_hp: 20, defense: 3, guard: 0.05, description: "A sturdy shield faced with the bark of the old road's guardian." },
});
Object.assign(recipes, {
  "moonlit poultice": { "moon herb": 2, meat: 1 },
  "salt ward": { "black salt": 2, silk: 1 },
  "clockwork charge": { "clockwork spring": 1, crystal: 1 },
  "sunfire bomb": { "ember core": 1, "moon herb": 1, coal: 1 },
  "trailbreaker bow": { steel: 3, "clockwork spring": 2, leather: 2 },
  bellguard: { steel: 3, "black salt": 2, "clockwork spring": 1 },
  "nullweave coat": { "enchanted silk": 3, "soul shard": 2, "void crystal": 2 },
  "archivist's ring": { "ancient crystal": 3, "soul shard": 2, gold: 2 },
  "margin seal": { "void crystal": 2, "ancient crystal": 2, "black salt": 3 },
  "last line tonic": { "ancient heart": 1, "moon herb": 4, "soul shard": 2 },
  "indexer's lens": { "ink fragment": 4, "soul shard": 3, "ancient crystal": 3 },
  "starfall aegis": { "star glass": 5, "glimmer wing": 2, "ancient crystal": 3 },
  ashglass: { "ashen sigil": 4, "ember core": 2, iron: 8 },
  "oathkeeper mail": { "oath fragment": 5, "ancient crystal": 4, "black salt": 3 },
  "outrider's bow": { "signal wire": 3, "clockwork spring": 2, leather: 3 },
  "choir veil": { "resonant bell": 2, silk: 3, "black salt": 2 },
  "reliquary guard": { "resonant bell": 3, "ashen sigil": 2, iron: 5 },
  "field stew": { meat: 2, "moon herb": 1 },
  "mosswrap boots": { "moss fiber": 3, leather: 2, fiber: 2 },
  "roadward charm": { "road pin": 1, leather: 2, "moon herb": 1 },
  "lantern charm": { "lantern glass": 2, silk: 2, iron: 1 },
  "mossback buckler": { "guardian bark": 3, iron: 3, leather: 2 },
});
Object.assign(SHOP_BUY, {
  "moon herb": 18, "black salt": 28, "clockwork spring": 32,
  "moonlit poultice": 55, "salt ward": 48, "clockwork charge": 60,
});
Object.assign(SHOP_SELL, {
  "moon herb": 8, "black salt": 12, "clockwork spring": 14,
  "moonlit poultice": 24, "salt ward": 20, "clockwork charge": 26,
  "sunfire bomb": 34, "margin seal": 58, "last line tonic": 75,
});


